### ISSUE TITLE
Support different metrics

### ISSUE THREAD

**Issue by JoeyHen** [psovea/api-backend#31]
In the future, the API will send different metrics to Prometheus, not just punctuality. These different metrics will have different Prometheus metric types (https://prometheus.io/docs/concepts/metric_types/). The JSON that is sent to the DB server will have to be changed to contain the metric type that the metric needs to support when this is done. For now the Gauge Metric Type is automatically used, with no support for others.

This will probably look something like:

{
    metrics: { punctuality: {value: 100, metric_type: gauge} },
    meta: {}
}

So only the value part of each metric will change from just a value to an array. This can be done next sprint. This will also need to be supported in the DB Server

**Comment by emilhaugberg** [comment]
Moved to https://github.com/psovea/db-server
